/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tron_leveldb_WriteBatch */

#ifndef _Included_org_tron_leveldb_WriteBatch
#define _Included_org_tron_leveldb_WriteBatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tron_leveldb_WriteBatch
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tron_leveldb_WriteBatch_close
  (JNIEnv *, jobject);

/*
 * Class:     org_tron_leveldb_WriteBatch
 * Method:    delete
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_tron_leveldb_WriteBatch_delete
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_tron_leveldb_WriteBatch
 * Method:    put
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_org_tron_leveldb_WriteBatch_put
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
