/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tron_leveldb_DB */

#ifndef _Included_org_tron_leveldb_DB
#define _Included_org_tron_leveldb_DB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tron_leveldb_DB
 * Method:    init
 * Signature: (Ljava/io/File;Lorg/tron/leveldb/Options;)V
 */
JNIEXPORT void JNICALL Java_org_tron_leveldb_DB_init
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_tron_leveldb_DB
 * Method:    iterator
 * Signature: (Lorg/tron/leveldb/ReadOptions;)Lorg/tron/leveldb/DBIterator;
 */
JNIEXPORT jobject JNICALL Java_org_tron_leveldb_DB_iterator
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_tron_leveldb_DB
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tron_leveldb_DB_close
  (JNIEnv *, jobject);

/*
 * Class:     org_tron_leveldb_DB
 * Method:    put
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_org_tron_leveldb_DB_put___3B_3B
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     org_tron_leveldb_DB
 * Method:    put
 * Signature: ([B[BZ)V
 */
JNIEXPORT void JNICALL Java_org_tron_leveldb_DB_put___3B_3BZ
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     org_tron_leveldb_DB
 * Method:    get
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_tron_leveldb_DB_get
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_tron_leveldb_DB
 * Method:    delete
 * Signature: ([BZ)V
 */
JNIEXPORT void JNICALL Java_org_tron_leveldb_DB_delete
  (JNIEnv *, jobject, jbyteArray, jboolean);

/*
 * Class:     org_tron_leveldb_DB
 * Method:    createWriteBatch
 * Signature: ()Lorg/tron/leveldb/WriteBatch;
 */
JNIEXPORT jobject JNICALL Java_org_tron_leveldb_DB_createWriteBatch
  (JNIEnv *, jobject);

/*
 * Class:     org_tron_leveldb_DB
 * Method:    write
 * Signature: (Lorg/tron/leveldb/WriteBatch;Z)V
 */
JNIEXPORT void JNICALL Java_org_tron_leveldb_DB_write
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     org_tron_leveldb_DB
 * Method:    getProperty
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tron_leveldb_DB_getProperty
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
