/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tron_leveldb_DBIterator */

#ifndef _Included_org_tron_leveldb_DBIterator
#define _Included_org_tron_leveldb_DBIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tron_leveldb_DBIterator
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tron_leveldb_DBIterator_close
  (JNIEnv *, jobject);

/*
 * Class:     org_tron_leveldb_DBIterator
 * Method:    seekToFirst
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tron_leveldb_DBIterator_seekToFirst
  (JNIEnv *, jobject);

/*
 * Class:     org_tron_leveldb_DBIterator
 * Method:    hasNext
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_tron_leveldb_DBIterator_hasNext
  (JNIEnv *, jobject);

/*
 * Class:     org_tron_leveldb_DBIterator
 * Method:    next
 * Signature: ()Ljava/util/Map/Entry;
 */
JNIEXPORT jobject JNICALL Java_org_tron_leveldb_DBIterator_next
  (JNIEnv *, jobject);

/*
 * Class:     org_tron_leveldb_DBIterator
 * Method:    peekNext
 * Signature: ()Ljava/util/Map/Entry;
 */
JNIEXPORT jobject JNICALL Java_org_tron_leveldb_DBIterator_peekNext
  (JNIEnv *, jobject);

/*
 * Class:     org_tron_leveldb_DBIterator
 * Method:    seekToLast
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tron_leveldb_DBIterator_seekToLast
  (JNIEnv *, jobject);

/*
 * Class:     org_tron_leveldb_DBIterator
 * Method:    hasPrev
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_tron_leveldb_DBIterator_hasPrev
  (JNIEnv *, jobject);

/*
 * Class:     org_tron_leveldb_DBIterator
 * Method:    prev
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tron_leveldb_DBIterator_prev
  (JNIEnv *, jobject);

/*
 * Class:     org_tron_leveldb_DBIterator
 * Method:    peekPrev
 * Signature: ()Ljava/util/Map/Entry;
 */
JNIEXPORT jobject JNICALL Java_org_tron_leveldb_DBIterator_peekPrev
  (JNIEnv *, jobject);

/*
 * Class:     org_tron_leveldb_DBIterator
 * Method:    seek
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_tron_leveldb_DBIterator_seek
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
